-- AI-generated draft content for EOT cases.
-- Stores liability assessments, proposed charges, tenant negotiation letters,
-- and combined reports generated by the AI assistant.

CREATE TABLE IF NOT EXISTS ai_drafts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  draft_type text NOT NULL CHECK (draft_type IN (
    'liability_assessment',
    'proposed_charges',
    'tenant_negotiation',
    'combined_report'
  )),
  title text,
  content text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}',
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- Each case can have one active draft per type
CREATE UNIQUE INDEX IF NOT EXISTS uq_ai_drafts_case_type_active
  ON ai_drafts (case_id, draft_type)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_ai_drafts_tenant_case
  ON ai_drafts (tenant_id, case_id);

CREATE INDEX IF NOT EXISTS idx_ai_drafts_case_deleted
  ON ai_drafts (case_id, deleted_at);

-- RLS
ALTER TABLE ai_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY ai_drafts_tenant_isolation ON ai_drafts
  USING (tenant_id = auth.uid()::uuid OR tenant_id IN (
    SELECT tenant_id FROM tenant_memberships
    WHERE user_id = auth.uid() AND deleted_at IS NULL
  ));
