-- Manual follow-up migration after knowledge cleanup verification.
-- Seeds additional Scotland-focused and end-of-tenancy guidance content into the
-- existing knowledge_articles schema without altering table structure.

insert into public.knowledge_articles (
  title,
  category,
  content,
  is_active,
  source_url,
  source_authority,
  jurisdiction,
  audience,
  article_kind,
  review_status,
  reviewed_at,
  keywords,
  updated_at
)
values
  (
    'Private Residential Tenancy — Scotland',
    'Scotland',
    'The Private Residential Tenancy applies to most new private tenancies in Scotland from 1 December 2017. It is open-ended rather than fixed-term in the usual sense, tenants can normally leave by giving notice, and landlords must rely on statutory grounds if they want possession. There is no Section 21 equivalent in Scotland. Older assured or short assured tenancies did not automatically convert just because the new regime started. For end-of-tenancy work, the practical need for strong inventories, check out evidence, photos, and proportionate deduction reasoning is much the same, but the surrounding legal framework is different from England and Wales.',
    true,
    'https://www.gov.scot/publications/private-residential-tenancies-tenants-guide/',
    'official',
    'scotland',
    array['operator'],
    'legal_summary',
    'approved',
    now(),
    array['scotland', 'private residential tenancy', 'prt', 'end of tenancy', 'deposit dispute'],
    now()
  ),
  (
    'Safe Deposits Scotland — How Disputes Work',
    'Scotland',
    'SafeDeposits Scotland disputes are handled through a scheme process where both parties may be invited to provide evidence. Managers should prepare the file before the dispute is raised where possible, because evidence windows are typically time-limited and timings can vary by scheme process and the completeness of submissions. The most persuasive material is usually a signed check in report, a check out report tied to the same rooms or items, dated photos, invoices or repair quotes, a clear written deduction summary, and relevant communication records. Good preparation matters more than volume.',
    true,
    'https://www.safedepositsscotland.com/',
    'official',
    'scotland',
    array['operator'],
    'process',
    'approved',
    now(),
    array['scotland', 'safe deposits scotland', 'dispute process', 'evidence', 'deductions'],
    now()
  ),
  (
    'First-tier Tribunal Scotland — Housing and Property Chamber',
    'Scotland',
    'The First-tier Tribunal for Scotland (Housing and Property Chamber) is the formal forum for many landlord-tenant disputes in Scotland. It may become relevant for deposit-protection non-compliance, formal tenancy disputes, and some higher-stakes contested matters. Scheme adjudication and tribunal proceedings are different processes, so managers should not assume the tribunal is a simple universal appeal route from a scheme decision. Tribunal proceedings are usually more formal and slower than ordinary scheme dispute handling, so the relevant scheme rules and legal advice should be checked where escalation is being considered.',
    true,
    'https://housingandpropertychamber.scot/',
    'official',
    'scotland',
    array['operator'],
    'legal_summary',
    'approved',
    now(),
    array['scotland', 'first-tier tribunal', 'housing and property chamber', 'deposit compliance', 'formal dispute'],
    now()
  ),
  (
    'Tenancy Deposit Protection — Scotland',
    'Scotland',
    'In Scotland, tenancy deposits generally need to be protected within 30 working days of the start of the tenancy, and the tenant must be given the required scheme information. The approved Scottish schemes are Safe Deposits Scotland, Letting Protection Service Scotland, and mydeposits Scotland. Non-compliance can lead to financial penalties, a weaker position at tenancy end, and more difficult dispute handling. For property managers, scheme name, reference, and protection timing should be part of the tenancy-end file before any deduction proposal is sent.',
    true,
    'https://www.mygov.scot/landlord-deposit/protection',
    'official',
    'scotland',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['scotland', 'deposit protection', '30 working days', 'approved schemes', 'scheme information'],
    now()
  ),
  (
    'Fair Wear and Tear in Scotland',
    'Scotland',
    'The core principle in Scotland is broadly similar to England and Wales: tenants are not usually liable for normal deterioration caused by reasonable use. In practice, longer-running private residential tenancies can make tenancy length especially important when deciding whether a loss is ordinary use or damage. Evidence quality remains critical and betterment still matters. Useful practical examples include older carpets, paint scuffs, condensation and mould in older properties, and other issues where responsibility may be shared rather than purely tenant-caused.',
    true,
    'https://www.mydeposits.co.uk/content-hub/fair-wear-and-tear-what-is-it-and-how-is-it-applied/',
    'official',
    'scotland',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['scotland', 'fair wear and tear', 'betterment', 'evidence quality', 'shared responsibility'],
    now()
  ),
  (
    'Letting Agent Regulation in Scotland',
    'Scotland',
    'Scottish letting agents must comply with the relevant registration and Code of Practice framework. For end-of-tenancy handling, the operational themes are strong record keeping, transparent communication, evidence-backed deductions, and a clear audit trail. Good records support manager review, make it easier to explain a decision to landlords and tenants, and reduce the need to reconstruct the reasoning later if the case is challenged.',
    true,
    'https://lettingagentregistration.gov.scot/about',
    'official',
    'scotland',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['scotland', 'letting agent regulation', 'code of practice', 'audit trail', 'record keeping'],
    now()
  ),
  (
    'Betterment — How to Apply It to Deposit Claims',
    'Deposit Schemes',
    'Betterment means awarding more than the landlord''s reasonable loss. A claim should not usually leave the landlord with something materially newer or better at the tenant''s expense. That means full replacement cost is often not appropriate for older carpets, decoration, or appliances. Managers should explain age, quality, and likely remaining life, then show how the figure was reduced. Lifespan examples are commonly used reference points, not fixed rules. Cleaning is different from replacement and depreciation issues and should be treated separately.',
    true,
    'https://www.mydeposits.co.uk/content-hub/rules-of-claiming-for-deposit-deductions/',
    'official',
    'uk',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['betterment', 'deposit claims', 'proportionality', 'lifespan', 'new for old'],
    now()
  ),
  (
    'Check In Reports — What Makes a Strong One',
    'Evidence and Documentation',
    'A strong check in report is often the most important document in a deposit dispute because it establishes the starting condition of the property. It should contain room-by-room written condition notes, dated photos, an inventory of contents where relevant, and tenant sign-off or a clear written opportunity to amend. Common weaknesses include vague descriptions, missing photos, failure to record pre-existing marks, and missing meter readings. If the opening report is thin, later deductions become much harder to prove.',
    true,
    'https://www.depositprotection.com/learning-centre/disputes/preparing-for-disputes-the-check-in',
    'official',
    'uk',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['check in report', 'inventory', 'dated photos', 'tenant sign off', 'evidence quality'],
    now()
  ),
  (
    'Check Out Reports — What to Include and How to Compare',
    'Evidence and Documentation',
    'A useful check out report compares the end condition back to the opening record rather than describing the property in isolation. It should use comparison-focused language, the same-angle photos where possible, specific cleaning and condition observations, meter readings, and timing close to the move out date. Subjective or emotional language should be avoided. The report should make it easy to understand exactly what changed and why a deduction is being proposed.',
    true,
    'https://www.depositprotection.com/press-releases/2022/student-tenant-checkout-tips',
    'official',
    'uk',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['check out report', 'comparison', 'move out', 'photos', 'cleaning assessment'],
    now()
  ),
  (
    'Communicating Deposit Deductions to Tenants',
    'Dispute Handling',
    'Proposed deductions should be communicated early, clearly, and in a professional tone so disputes are less likely to escalate. A good message explains each line item, the amount proposed, the reason for it, and the evidence that supports it. Managers should keep a written record of what was sent and when. Clear, evidence-linked communication often reduces disagreement because tenants can see how the decision was reached before the matter moves into a formal dispute process.',
    true,
    'https://custodial.tenancydepositscheme.com/tools-and-guides/user-guides/all-users/deposit-deductions-template',
    'official',
    'uk',
    array['operator'],
    'guidance',
    'approved',
    now(),
    array['communication', 'deposit deductions', 'line items', 'tenant correspondence', 'dispute prevention'],
    now()
  )
on conflict (source_url) do update
set
  title = excluded.title,
  category = excluded.category,
  content = excluded.content,
  is_active = excluded.is_active,
  source_authority = excluded.source_authority,
  jurisdiction = excluded.jurisdiction,
  audience = excluded.audience,
  article_kind = excluded.article_kind,
  review_status = excluded.review_status,
  reviewed_at = excluded.reviewed_at,
  keywords = excluded.keywords,
  updated_at = now();
